[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    https://github.com/h2zero/NimBLE-Arduino.git
    bblanchon/ArduinoJson@^6.21.3
    firebase-arduino/FirebaseJson@^2.6.4

build_flags = 
    -D CORE_DEBUG_LEVEL=3
